#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 18:52:10 2019

@author: rick
"""

import pandas as pd
import folium 
import os
#%%

## Make sure that this will run on its own.
state_geo = os.path.join('/Users/rick/Desktop/', 'us-states.json')
#%%
my_USA_map = '/Users/rick/Desktop/us_states.json'
my_dataframe = pd.read_csv("Mortalities.csv")
#my_dataframe.set_index("States", inplace=True)

#%%

# Initialize the map:
m = folium.Map(location=[37, -102], zoom_start=5)
 
# Add the color for the chloropleth:
m.choropleth(
 geo_data=state_geo,
 name='choropleth',
 data=my_dataframe,
 columns=['States', 'Total Change'],
 key_on='feature.id',
 fill_color='YlGn',
 fill_opacity=0.7,
 line_opacity=0.2,
 legend_name='Total Change in Mortalities'
)
folium.LayerControl().add_to(m)

m.save('Mortality_Map.html')

#%%

pdata2013 = pd.read_csv("medicare-part-d-opioid-prescriber-summary-file-2013.csv")
#%%
pdata2016 = pd.read_csv("medicare-part-d-opioid-prescriber-summary-file-2016.csv")
#%%


pdatagrouped2013 = pdata2013.groupby("NPPES Provider State").sum()

pdatacut2013 = pdatagrouped2013.iloc[:,3]


#%%

pdatagrouped2016 = pdata2016.groupby("NPPES Provider State").sum()

pdatacut2016 = pdatagrouped2016.iloc[:,3]


#%%


combined = pdatacut2016.subtract(pdatacut2013)


#%%
m = folium.Map(location=[37, -102], zoom_start=5)
 
# Add the color for the chloropleth:
m.choropleth(
 geo_data=state_geo,
 name='choropleth',
 data=combined,
 columns=['NPPES Provider State', 'Opioid Claim Count'],
 key_on='feature.id',
 fill_color='YlGn',
 fill_opacity=0.7,
 line_opacity=0.2,
 legend_name='Total Change in Prescriptions'
)
folium.LayerControl().add_to(m)

m.save('Prescription_Map.html')












